# Generated by Django 4.0.1 on 2022-02-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_post_projectprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date']},
        ),
    ]
