# Generated by Django 4.0.1 on 2022-02-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_category_delete_post_alter_newsstory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
