# Generated by Django 4.0.1 on 2022-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('PROGRAM', 'Program'), ('ANNOUNCEMENTS', 'Announcements')], default='news', max_length=200),
        ),
    ]
