# Generated by Django 4.0.1 on 2022-02-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsstory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
    ]
