# Generated by Django 4.0.1 on 2022-02-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_newsstory_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='categories',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('PROGRAM', 'Program'), ('ANNOUNCEMENTS', 'Announcements'), ('CAREERS', 'Careers')], default='news', max_length=200),
        ),
    ]
